### ISSUE TITLE
Ability to compute through AMOS gateway across multiple remote resources.

### ISSUE THREAD

**Issue by eroma2014** [GT-Nexus/AMOS-Gateway#19]
- [ ] Goal 1: [Configure AMOS applications in the gateway. ](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/2)
- [ ] Goal 2: [Configure ACCESS resources and other shared resources into the gateway and configure the communication.](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/20)
- [ ] Goal 3: [Test all the application executions and file transfers through the AMOS gateway. ](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/1)
