### ISSUE TITLE
UI workflows for AMOS applications to improve user experience.

### ISSUE THREAD

**Issue by eroma2014** [GT-Nexus/AMOS-Gateway#22]
- [ ] Goal 1: Ensure end-to-end successful completion of tRecX workflow execution with existing UI application.  
- [ ] Goal 2: [XChem UI workflow development in AMOS gateway ](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/26)
- [ ] Goal 3: [UX design for EPolyScat application](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/24) 
- [ ] Goal 4: [EPolyScat UI workflow development ](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/25)
- [ ] Goal 5: [UKRMol+ user interface design](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/5) 
- [ ] Goal 6: [UKRMol+ UI workflow development](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/23) 
- [ ] Goal 7: [RMT user interface design](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/12) 
- [ ] Goal 8: [RMT UI workflow development](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/13) 
- [ ] Goal 9: [MESA user interface design](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/27) 
- [ ] Goal 10: [MESA application UI workflow implementation](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/28). 
- [ ] Goal 11: [BSR user interface design](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/29) 
- [ ] Goal 12: [BSR UI interface workflow development and release](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/30) 
- [ ] Goal 13: [CCC user interface design](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/31) 
- [ ] Goal 14: [CCC UI interface workflow development and release](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/32) 
- [ ] Goal 15: [GRASP user interface design](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/33) 
- [ ] Goal 16: [GRASP UI interface workflow development and release](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/34)
