### ISSUE TITLE
Implement databases to store and use experimental and computational data. 

### ISSUE THREAD

**Issue by eroma2014** [GT-Nexus/AMOS-Gateway#36]
Implement databases to store and use experimental and computational data. 

- [ ] Goal 1: [Gather requirements on data ingestion methods and obtain access to the external databases and data ](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/37) 
- [ ] Goal 2: [Design the experimental DB and Computational DB meta data ](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/38)
- [ ] Goal 3: [Implement and launch experimental and computational data catalogs for AMOS gateway](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/9)
