### ISSUE TITLE
Visualize AMOS computational outputs for jobs

### ISSUE THREAD

**Issue by eroma2014** [GT-Nexus/AMOS-Gateway#39]
Users should be able to visualize the output when a job is active and/or completed. 

- [ ] Goal 1: [Implement remote visualization for active and completed jobs within AMOS gateway ](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/7)
- [ ] Goal 2: [Integrate gateway level visualization for gateway-initiated jobs](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/40) 
- [ ] Goal 3: [Enable analysis post visualization ](https://github.com/GT-ARTISAN/AMOS-Gateway/issues/41)
